---
version: '3'
services:
  # IBM MQ
  # doc https://github.com/ibm-messaging/mq-container/blob/master/docs/developer-config.md
  ibm-mq:
    image: ibmcom/mq:9
    environment:
      LICENSE: accept
      MQ_QMGR_NAME: QM1
      #      Prometheus metrics, exposed on :9157/metrics
      MQ_ENABLE_METRICS: "true"
      MQ_APP_PASSWORD: "passw0rd"
    ports:
      - 1414:1414
      - 9443:9443
      - 9157:9157
#    volumes:
#      - mq-data:/mnt/mqm

  kafka:
    image: landoop/fast-data-dev
    environment:
      ADV_HOST: localhost    # Change to 192.168.99.100 if using Docker Toolbox or leave localhost
      RUNTESTS: 0                 # Disable Running tests so the cluster starts faster
    ports:
      - "2181:2181"                 # Zookeeper
      - "3030:3030"                 # Landoop UI
      - "8081-8083:8081-8083"       # REST Proxy, Schema Registry, Kafka Connect ports
      - "9581-9585:9581-9585"       # JMX Ports
      - "9092:9092"                 # Kafka Broker